# CircleCI 2.0 configuration file
#
version: 2
jobs:
# Disable goveralls to make build work when merging from forks
#      - run: /go/bin/goveralls -coverprofile=coverage-all.out -service=circle-ci -repotoken=$COVERALLS_TOKEN

  build_ui:
    working_directory: ~/mobile-developer-console
    docker:
      - image: circleci/node:dubnium

    steps:
      - checkout
      - run: make check-code-style
      - run: make test-cover
      - run: make build


  docker_push_master:
    working_directory: ~/mobile-developer-console
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - run: make build
      - run: make docker_build_master
      - run: make docker_push_master

  docker_release:
    working_directory: ~/mobile-developer-console
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - run: make build
      - run: make docker_build_release
      - run: make docker_push_release

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_ui:
          filters:
            tags:
              only: /.*/
      - docker_push_master:
          requires:
            - build_ui
          filters:
            branches:
              only:
                - master
      - docker_release:
          requires:
            - build_ui
          filters:
            tags:
              only: /\d\.\d\.\d(.*?)/
            branches:
              ignore: /.*/
